pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }

        stage('Build') { 
            steps { 
                script{
                 app = docker.build("underwater")
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Deploy') {
            steps {
                script{
                        def ecr_credentials = "QVdTOmV5SndZWGxzYjJGa0lqb2ljVWRzVVZCbmJtZGFTbHBNWWtSTmVtaHZabTAzU21wd1NWTTBMM0ppVGxvd1RXeEhUakpPYlhRMVQwbFhVSFF4TjBSclRteE1hRkpZV2pBNGIwdzFha2t4WkhkUWRHRmtaM0ZLVDNaRVlXNDNWbEJJUjNSWFZrdDFWSEJVWVhOa1FtY3ZLelpSTkd4S1RWaGpZVVpOYmxOMlRIVnBiRTV6TVhSMk5WRkVXbmswU20xSVpraFhNM1pRVGpFM2QzZHRZMU53ZEd0YWVEUTNUelJ5ZEUwNGFHWk1RbFZZWkZGeE1FVXhaVFlyVEdkamNWcHBUMXBoZGxSd1lTODBUak5OUXpSNWJHMUNRVzV5VkVsYWRqZHVhM1JwUlRKblFXWkNiVlJHVTJNdmJsRnVlVEYwUjFvNU1XTnhWRXR1TkRkMGRFSjFaU3RsVUhRdk5sQmhZa2d5UVRGalNXWjFTbE5zZUZKRWJFbFlNSGhZT0RnMmFsWllRa0pCZEZVeWRXaExiR1pEY1VaWVN6TkpWMDlzY1VkNU5FUTJibTB2YnpCelZXWnRTbTUwZW1kRGJuSlBOM2d5Ymk5clJrTTJWV3d2U2tjdmIwZDNjSGhEZVVwc1NITlFRMjFuUWpjellVSnJjRU5hZG01blUyMXVVV042U20wM2R6ZFdaRGt3U1ZGVlEyUkRaV0U0VlZWelkyNDJUVkoyYzFoTGFtMVhiMWd6WjJ0TlNXWmlUMlV2VTJoWWVrdHJia3RLZWxWeEsybFdVbmR2Tm14TU4yZGlZMUp2TjB0RVNWQlNVRXhRTTFBNVFUQnRia1pUWVhKcVdWTXlMMmN5V1ZCeFowNUhSazF6UWk4d1dsSTFNME5MWmxoWVoxTk1TU3RLZWpScGNuSTJOemxIYlVreVUxcENVVWh2Y0U1clQzTnFiWGxIY0RKSWNqazJZbFp4WTBGUmVGWm1TVGRvVDJGS04ybzBjMWhtY0hGcVRuaHFhUzgzVm5rck5IaEZSME0yZWxVdlNIRkhWRE5TWjBkU1EzY3hSekU1TW5NM2N6QlVUazFXYkM5WVVqRXdObGRUTURGVlYxQTRSU3RzVTNRcmVHazBORGROTVZaeVJXUkllVVZRZEV0T1ZFOHZSVzlWVkVKM2NHVkxSREoyT0hoRVVDdExTRE5VVG1OM1dqTkVPWEE0U1VRMFlqZHpOWGcyTWxZeFlYbDFORWhXVkRGM05DOWllVk5XYlVzemExTm1LMlpsU2tSa1FTczNWRWhNTWxCNVNHNU1jRUpZUzAxQ2NXdExVRFp2WmxsTlNWTjRjSEoxVDBSMGJ6VlBiRlJ0UWpGdE9UWnRiMFZXUlhOYWVHOXJiVXRDTkhoNmRscGlLMXBIWldZelRFRk5hVXRKUkVKRk5URnpRMFpHSzBNd1JGUlZNbmQxU1RoU01XdFVWMUF6VGsxM1YyMXpjVXhFVW5rdk9IRkJVR1phUlc0d09HSk1VblE0WVZOc2JscEVOWGRFZUdkVlRtcHJObkphVDFwb1kyOTJRU3RYWW5wSmMwWmtURFZUV2xoaFdXNVdVVU5VUTJwRlIxWmtNSFE0Y1RGVE1WZGxhMUpLVTFnMFVXZHFjWGh2VlZSUVJYQjVRekZXYzJ4SlZYcG1kM05OZUVzNGNDOHpOVWx2Tms0MGFIZ3dXa1ZhWW5sb1Z5dDJkMmxQWW0xbFlYZDZhbWhsVFhoSlQyVmxXV1JTV214eGNXdDZWbmxYVlZORFlXa3pUWEJxYW1vd1NGRnZPVkIwVDIwNUswRmpia0p6TlZWaVZXZExSemh1TDFkNmFXRXpNa0pDTVhSR2R6ZGtiVk5aY1dodmVIVTRTaXR2TTI5VE1DdE1ZVlYxVjJGaVozSTRlWG8yVTFSUVRHUXZlR1ZoTlZKTGNrazlJaXdpWkdGMFlXdGxlU0k2SWtGUlNVSkJTR2hCVDNOaFZ6Sm5XazR3T1ZkT2RFNUhhMWxqT0hGd01URjRVMmhhTDJSeVJVVnZlVEZJYXpoTVdGZG5SV05PSzFKdWFtaDBhbVpNTUc1U05HeHRLMUppVlVGQlFVRm1ha0k0UW1kcmNXaHJhVWM1ZHpCQ1FuZGhaMko2UW5SQlowVkJUVWRuUjBOVGNVZFRTV0l6UkZGRlNFRlVRV1ZDWjJ4bmFHdG5RbHBSVFVWQlV6UjNSVkZSVFdobWJtWktTbmcyV0VNeGJGTlJOa0ZCWjBWUlowUjJTVEI0VGtRNFFuY3JaalpzZDNSRmMwVk1ZbVpTTW1wemVFWlhhbXhvTWpGblFqQkRhbk5RU1haaFpFdHdNM1p4ZUdGWldtaFVSMU5CY3pOMGVteDZWVlJTVVdKM2NsQTJhRWMwZEhkbGR6MDlJaXdpZG1WeWMybHZiaUk2SWpJaUxDSjBlWEJsSWpvaVJFRlVRVjlMUlZraUxDSmxlSEJwY21GMGFXOXVJam94TmpreE5EY3pNVE00ZlE9PQ=="
                        docker.withRegistry('https://383468065570.dkr.ecr.ap-northeast-2.amazonaws.com','ecr:ap-northeast-2:${ecr_credentials}') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")
                    }
                }
            }
        }
    }
}
